# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=3)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('RequestedHours', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='SubjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_shift_id', to='schedule.Subject'),
        ),
        migrations.AddField(
            model_name='shift',
            name='TutorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_shift_id', to='schedule.Tutor'),
        ),
    ]
