# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180409_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='SubjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='schedule.Subject'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='TutorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='schedule.Tutor'),
        ),
    ]
