# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20180409_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='RequestedHours',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
