# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20180411_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['Day', 'StartTime', 'SubjectID']},
        ),
    ]
