# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20180411_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='SubjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftSubject', to='schedule.Subject'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='TutorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftTutor', to='schedule.Tutor'),
        ),
    ]
