# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_tutor_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='following',
            new_name='TutorForCourse',
        ),
    ]
