# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20180428_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='Day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Monday', 'Tuesday'), ('Tuesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shift',
            name='Day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Monday', 'Tuesday'), ('Tuesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20),
        ),
    ]
