# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_auto_20180501_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='TutorImage',
            field=models.ImageField(default='/media/profiles/empty-profile.png', upload_to=''),
        ),
    ]
