# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_auto_20180501_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='TutorImage',
        ),
    ]
